//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/es/gob/jmulticard/asn1/icao/AdditionalPersonalDetails.java
//

#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "es/gob/jmulticard/HexUtils.h"
#include "es/gob/jmulticard/JmcLogger.h"
#include "es/gob/jmulticard/asn1/DecoderObject.h"
#include "es/gob/jmulticard/asn1/Tlv.h"
#include "es/gob/jmulticard/asn1/TlvException.h"
#include "es/gob/jmulticard/asn1/icao/AdditionalPersonalDetails.h"
#include "java/io/ByteArrayInputStream.h"
#include "java/io/ByteArrayOutputStream.h"
#include "java/io/DataInputStream.h"
#include "java/io/IOException.h"
#include "java/lang/StringBuilder.h"

#if !__has_feature(objc_arc)
#error "es/gob/jmulticard/asn1/icao/AdditionalPersonalDetails must be compiled with ARC (-fobjc-arc)"
#endif

@interface EsGobJmulticardAsn1IcaoAdditionalPersonalDetails () {
 @public
  /*!
   @brief Nombre completo del titular.
   */
  NSString *subjectFullName_;
  /*!
   @brief N&uacute;mero personal.
   */
  NSString *personalNumber_;
  /*!
   @brief Fecha de nacimiento completa (en formato <i>aaaammdd</i>).
   */
  NSString *fullBirthDate_;
  /*!
   @brief Lugar de nacimiento.
   */
  NSString *birthPlace_;
  /*!
   @brief Direcci&oacute;n.
   */
  NSString *residenceAddress_;
  /*!
   @brief Ciudad.
   */
  NSString *residenceCity_;
  /*!
   @brief Provincia.
   */
  NSString *residenceProvince_;
}

+ (IOSByteArray *)readNBytesWithJavaIoDataInputStream:(JavaIoDataInputStream *)dis
                                              withInt:(jint)nBytes;

- (void)processFieldWithByte:(jbyte)type
               withByteArray:(IOSByteArray *)value;

@end

J2OBJC_FIELD_SETTER(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails, subjectFullName_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails, personalNumber_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails, fullBirthDate_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails, birthPlace_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails, residenceAddress_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails, residenceCity_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails, residenceProvince_, NSString *)

inline jbyte EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_get_TAG(void);
#define EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_TAG 107
J2OBJC_STATIC_FIELD_CONSTANT(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails, TAG, jbyte)

__attribute__((unused)) static IOSByteArray *EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_readNBytesWithJavaIoDataInputStream_withInt_(JavaIoDataInputStream *dis, jint nBytes);

__attribute__((unused)) static void EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_processFieldWithByte_withByteArray_(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails *self, jbyte type, IOSByteArray *value);

#line 1 "/Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/es/gob/jmulticard/asn1/icao/AdditionalPersonalDetails.java"


#line 17
@implementation EsGobJmulticardAsn1IcaoAdditionalPersonalDetails

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 17
- (instancetype)init {
  EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 44
- (NSString *)getSubjectFullName {
  return self->subjectFullName_;
}


#line 50
- (NSString *)getPersonalNumber {
  return self->personalNumber_;
}


#line 56
- (NSString *)getFullBirthDate {
  return self->fullBirthDate_;
}


#line 62
- (NSString *)getBirthPlace {
  return self->birthPlace_;
}


#line 70
- (NSString *)getResidenceAddress {
  return self->residenceAddress_;
}


#line 78
- (NSString *)getResidenceCity {
  return self->residenceCity_;
}


#line 86
- (NSString *)getResidenceProvince {
  return self->residenceProvince_;
}

- (void)decodeValue {
  
#line 92
  [self checkTagWithByte:IOSByteArray_Get(nil_chk([self getBytes]), 0)];
  
#line 94
  JavaIoDataInputStream *dis = new_JavaIoDataInputStream_initWithJavaIoInputStream_(new_JavaIoByteArrayInputStream_initWithByteArray_(
#line 96
  [new_EsGobJmulticardAsn1Tlv_initWithByteArray_([self getBytes]) getValue]));
  
#line 100
  @try {
    jbyte tag;
    jbyte len;
    
#line 104
    while ([dis available] > 2) {
      tag = [dis readByte];
      if (tag == (jint) 0x5f) {
        jbyte type = [dis readByte];
        len = [dis readByte];
        EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_processFieldWithByte_withByteArray_(self, type, EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_readNBytesWithJavaIoDataInputStream_withInt_(dis, len));
      }
      else {
        
#line 113
        len = [dis readByte];
        (void) EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_readNBytesWithJavaIoDataInputStream_withInt_(dis, len);
      }
    }
  }
  @catch (JavaIoIOException *e) {
    @throw new_EsGobJmulticardAsn1TlvException_initWithNSString_withJavaLangThrowable_(@"Error procesando el contenido del DG11", e);
  }
}


#line 124
+ (IOSByteArray *)readNBytesWithJavaIoDataInputStream:(JavaIoDataInputStream *)dis
                                              withInt:(jint)nBytes {
  return EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_readNBytesWithJavaIoDataInputStream_withInt_(dis, nBytes);
}


#line 132
- (jbyte)getDefaultTag {
  
#line 134
  return EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_TAG;
}


#line 137
- (NSString *)description {
  
#line 139
  JavaLangStringBuilder *sb = new_JavaLangStringBuilder_initWithNSString_(@"Detalles personales adidionales:");
  if (self->subjectFullName_ != nil) {
    (void) [sb appendWithNSString:@"\n  Nombre completo del titular: "];
    (void) [sb appendWithNSString:self->subjectFullName_];
  }
  if (self->personalNumber_ != nil) {
    (void) [sb appendWithNSString:@"\n  Numero personal: "];
    (void) [sb appendWithNSString:self->personalNumber_];
  }
  if (self->fullBirthDate_ != nil) {
    (void) [sb appendWithNSString:@"\n  Fecha de nacimiento completa: "];
    (void) [sb appendWithNSString:self->fullBirthDate_];
  }
  if (self->birthPlace_ != nil) {
    (void) [sb appendWithNSString:@"\n  Lugar de nacimiento: "];
    (void) [sb appendWithNSString:self->birthPlace_];
  }
  if (self->residenceAddress_ != nil) {
    (void) [sb appendWithNSString:@"\n  Direccion: "];
    (void) [sb appendWithNSString:self->residenceAddress_];
  }
  if (self->residenceCity_ != nil) {
    (void) [sb appendWithNSString:@"\n  Ciudad: "];
    (void) [sb appendWithNSString:self->residenceCity_];
  }
  if (self->residenceProvince_ != nil) {
    (void) [sb appendWithNSString:@"\n  Provincia: "];
    (void) [sb appendWithNSString:self->residenceProvince_];
  }
  return [sb description];
}


#line 171
- (void)processFieldWithByte:(jbyte)type
               withByteArray:(IOSByteArray *)value {
  EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_processFieldWithByte_withByteArray_(self, type, value);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, 0, -1, -1, -1 },
    { NULL, "[B", 0xa, 1, 2, 3, -1, -1, -1 },
    { NULL, "B", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 4, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 5, 6, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getSubjectFullName);
  methods[2].selector = @selector(getPersonalNumber);
  methods[3].selector = @selector(getFullBirthDate);
  methods[4].selector = @selector(getBirthPlace);
  methods[5].selector = @selector(getResidenceAddress);
  methods[6].selector = @selector(getResidenceCity);
  methods[7].selector = @selector(getResidenceProvince);
  methods[8].selector = @selector(decodeValue);
  methods[9].selector = @selector(readNBytesWithJavaIoDataInputStream:withInt:);
  methods[10].selector = @selector(getDefaultTag);
  methods[11].selector = @selector(description);
  methods[12].selector = @selector(processFieldWithByte:withByteArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "TAG", "B", .constantValue.asChar = EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_TAG, 0x1a, -1, -1, -1, -1 },
    { "subjectFullName_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "personalNumber_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "fullBirthDate_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "birthPlace_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "residenceAddress_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "residenceCity_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "residenceProvince_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LEsGobJmulticardAsn1Asn1Exception;LEsGobJmulticardAsn1TlvException;", "readNBytes", "LJavaIoDataInputStream;I", "LJavaIoIOException;", "toString", "processField", "B[B" };
  static const J2ObjcClassInfo _EsGobJmulticardAsn1IcaoAdditionalPersonalDetails = { "AdditionalPersonalDetails", "es.gob.jmulticard.asn1.icao", ptrTable, methods, fields, 7, 0x11, 13, 8, -1, -1, -1, -1, -1 };
  return &_EsGobJmulticardAsn1IcaoAdditionalPersonalDetails;
}

@end


#line 17
void EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_init(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails *self) {
  EsGobJmulticardAsn1DecoderObject_init(self);
  self->subjectFullName_ =
#line 22
  nil;
  self->personalNumber_ =
#line 25
  nil;
  self->fullBirthDate_ =
#line 28
  nil;
  self->birthPlace_ =
#line 31
  nil;
  self->residenceAddress_ =
#line 34
  nil;
  self->residenceCity_ =
#line 37
  nil;
  self->residenceProvince_ =
#line 40
  nil;
}


#line 17
EsGobJmulticardAsn1IcaoAdditionalPersonalDetails *new_EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_init() {
  J2OBJC_NEW_IMPL(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails, init)
}


#line 17
EsGobJmulticardAsn1IcaoAdditionalPersonalDetails *create_EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_init() {
  J2OBJC_CREATE_IMPL(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails, init)
}


#line 124
IOSByteArray *EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_readNBytesWithJavaIoDataInputStream_withInt_(JavaIoDataInputStream *dis, jint nBytes) {
  EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_initialize();
  
#line 125
  JavaIoByteArrayOutputStream *baos = new_JavaIoByteArrayOutputStream_init();
  for (jint i = 0; i < nBytes; i++) {
    [baos writeWithInt:[((JavaIoDataInputStream *) nil_chk(dis)) readByte]];
  }
  return [baos toByteArray];
}


#line 171
void EsGobJmulticardAsn1IcaoAdditionalPersonalDetails_processFieldWithByte_withByteArray_(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails *self, jbyte type, IOSByteArray *value) {
  {
    
#line 186
    NSString *fullAddress;
    
#line 188
    IOSObjectArray *addressParticles;
    
#line 172
    switch (type) {
      case (jint) 0x0e:
      self->subjectFullName_ = [NSString java_stringWithBytes:value];
      break;
      case (jint) 0x10:
      self->personalNumber_ = [NSString java_stringWithBytes:value];
      break;
      case (jint) 0x2b:
      self->fullBirthDate_ = EsGobJmulticardHexUtils_hexifyWithByteArray_withBoolean_(value, false);
      break;
      case (jint) 0x11:
      self->birthPlace_ = [NSString java_stringWithBytes:value];
      break;
      case (jint) 0x42:
      fullAddress = [NSString java_stringWithBytes:value];
      addressParticles =
#line 188
      [fullAddress java_split:@"<"];
      self->residenceAddress_ = IOSObjectArray_Get(nil_chk(addressParticles), 0);
      if (addressParticles->size_ >= 2) {
        self->residenceCity_ = IOSObjectArray_Get(addressParticles, 1);
      }
      if (addressParticles->size_ >= 3) {
        self->residenceProvince_ = IOSObjectArray_Get(addressParticles, 2);
      }
      break;
      default:
      EsGobJmulticardJmcLogger_warningWithNSString_(JreStrcat("$$", @"Rotulo de DG11 no soportado: 5F", EsGobJmulticardHexUtils_hexifyWithByteArray_withBoolean_([IOSByteArray newArrayWithBytes:(jbyte[]){ type } count:1], false)));
    }
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EsGobJmulticardAsn1IcaoAdditionalPersonalDetails)
