//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/es/gob/jmulticard/ios/DnieInfo.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EsGobJmulticardIosDnieInfo")
#ifdef RESTRICT_EsGobJmulticardIosDnieInfo
#define INCLUDE_ALL_EsGobJmulticardIosDnieInfo 0
#else
#define INCLUDE_ALL_EsGobJmulticardIosDnieInfo 1
#endif
#undef RESTRICT_EsGobJmulticardIosDnieInfo

#if !defined (EsGobJmulticardIosDnieInfo_) && (INCLUDE_ALL_EsGobJmulticardIosDnieInfo || defined(INCLUDE_EsGobJmulticardIosDnieInfo))
#define EsGobJmulticardIosDnieInfo_

@class IOSByteArray;

/*!
 @brief Informaci&oacute;n extra&iacute;da del DNIe.
 */
@interface EsGobJmulticardIosDnieInfo : NSObject

#pragma mark Public

- (instancetype)init;

/*!
 @brief Recupera la ciudad de nacimiento de la persona.
 @return Ciudad de nacimiento de la persona.
 */
- (NSString *)getBirthCity;

/*!
 @brief Recupera el pa&iacute;s de nacimiento de la persona.
 @return Pa&iacute;s de nacimiento de la persona.
 */
- (NSString *)getBirthCountry;

/*!
 @brief Recupera la provincia de nacimiento de la persona.
 @return Provincia de nacimiento de la persona.
 */
- (NSString *)getBirthProvince;

/*!
 @brief Recupera la fecha de nacimiento de la persona.
 @return Fecha de nacimiento de la persona.
 */
- (NSString *)getDateOfBirth;

/*!
 @brief Recupera la fecha de caducidad de la persona.
 @return Fecha de caducidad de la persona.
 */
- (NSString *)getDateOfExpiry;

/*!
 @brief Recupera n&uacute;mero de DNI.
 @return N&uacute;mero de DNI.
 */
- (NSString *)getDniNumber;

/*!
 @brief Recupera n&uacute;mero de documento.
 @return N&uacute;mero de documento.
 */
- (NSString *)getDocNumber;

/*!
 @brief Recupera la fotogr&iacute;a de la cara de la persona.
 @return Fotogr&iacute;a de la cara de la persona en formato JPEG2000.
 */
- (IOSByteArray *)getFacePhoto;

/*!
 @brief Recupera el g&eacute;nero de la persona.
 @return G&eacute;nero de la persona.
 */
- (NSString *)getGender;

/*!
 @brief Recupera el nombre de la persona.
 @return Nombre de la persona.
 */
- (NSString *)getName;

/*!
 @brief Recupera la nacionalidad de la persona.
 @return Nacionalidad de la persona.
 */
- (NSString *)getNationality;

/*!
 @brief Recupera la direcci&oacute;n de residencia de la persona.
 @return Direcci&oacute;n de residencia de la persona.
 */
- (NSString *)getResidenceAddress;

/*!
 @brief Recupera la ciudad de residencia de la persona.
 @return Ciudad de residencia de la persona.
 */
- (NSString *)getResidenceCity;

/*!
 @brief Recupera la direcci&oacute;n de la persona.
 @return Direcci&oacute;n de la persona.
 */
- (NSString *)getResidenceProvince;

/*!
 @brief Recupera la fotogr&iacute;a de la firma de la persona.
 @return Fotogr&iacute;a de la firma de la persona en formato JPEG2000.
 */
- (IOSByteArray *)getSignaturePhoto;

/*!
 @brief Recupera el apellido de la persona.
 @return Apellido de la persona.
 */
- (NSString *)getSurname;

#pragma mark Package-Private

/*!
 @brief Establece la ciudad de nacimiento de la persona.
 @param birthCity Ciudad de nacimiento de la persona.
 */
- (void)setBirthCityWithNSString:(NSString *)birthCity;

/*!
 @brief Establece el pa&iacute;s de nacimiento de la persona.
 @param birthCountry Pa &iacute; s de nacimiento de la persona.
 */
- (void)setBirthCountryWithNSString:(NSString *)birthCountry;

/*!
 @brief Establece la provincia de nacimiento de la persona.
 @param birthProvince Provincia de nacimiento de la persona.
 */
- (void)setBirthProvinceWithNSString:(NSString *)birthProvince;

/*!
 @brief Establece la fecha de nacimiento de la persona.
 @param dateOfBirth Fecha de nacimiento de la persona.
 */
- (void)setDateOfBirthWithNSString:(NSString *)dateOfBirth;

/*!
 @brief Establece la fecha de caducidad de la persona.
 @param dateOfExpiry Fecha de caducidad de la persona.
 */
- (void)setDateOfExpiryWithNSString:(NSString *)dateOfExpiry;

/*!
 @brief Establece n&uacute;mero de DNI.
 @param dniNumber N &uacute; mero de DNI.
 */
- (void)setDniNumberWithNSString:(NSString *)dniNumber;

/*!
 @brief Establece el n&uacute;mero de documento.
 @param docNumber N &uacute; mero de documento.
 */
- (void)setDocNumberWithNSString:(NSString *)docNumber;

/*!
 @brief Establece la fotogr&iacute;a de la cara de la persona.
 @param facePhoto Fotogr &iacute; a de la cara de la persona en formato JPEG2000.
 */
- (void)setFacePhotoWithByteArray:(IOSByteArray *)facePhoto;

/*!
 @brief Establece el g&eacute;nero de la persona.
 @param gender G &eacute; nero de la persona.
 */
- (void)setGenderWithNSString:(NSString *)gender;

/*!
 @brief Establece el nombre de la persona.
 @param name Nombre de la persona.
 */
- (void)setNameWithNSString:(NSString *)name;

/*!
 @brief Establece la nacionalidad de la persona.
 @param nationality Nacionalidad de la persona.
 */
- (void)setNationalityWithNSString:(NSString *)nationality;

/*!
 @brief Establece la direcci&oacute;n de residencia de la persona.
 @param residenceProvince Direcci &oacute; n de residencia de la persona.
 */
- (void)setResidenceAddressWithNSString:(NSString *)residenceProvince;

/*!
 @brief Establece la ciudad de residencia de la persona.
 @param residenceProvince Ciudad de residencia de la persona.
 */
- (void)setResidenceCityWithNSString:(NSString *)residenceProvince;

/*!
 @brief Establece la provincia de residencia de la persona.
 @param residenceProvince Provincia de residencia de la persona.
 */
- (void)setResidenceProvinceWithNSString:(NSString *)residenceProvince;

/*!
 @brief Establece la fotogr&iacute;a de la firma de la persona.
 @param signaturePhoto Fotogr &iacute; a de la firma de la persona en formato JPEG2000.
 */
- (void)setSignaturePhotoWithByteArray:(IOSByteArray *)signaturePhoto;

/*!
 @brief Establece el apellido de la persona.
 @param surname Apellido de la persona.
 */
- (void)setSurnameWithNSString:(NSString *)surname;

@end

J2OBJC_EMPTY_STATIC_INIT(EsGobJmulticardIosDnieInfo)

FOUNDATION_EXPORT void EsGobJmulticardIosDnieInfo_init(EsGobJmulticardIosDnieInfo *self);

FOUNDATION_EXPORT EsGobJmulticardIosDnieInfo *new_EsGobJmulticardIosDnieInfo_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT EsGobJmulticardIosDnieInfo *create_EsGobJmulticardIosDnieInfo_init(void);

J2OBJC_TYPE_LITERAL_HEADER(EsGobJmulticardIosDnieInfo)

#endif

#pragma pop_macro("INCLUDE_ALL_EsGobJmulticardIosDnieInfo")
