//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/es/gob/jmulticard/ios/DnieFactoryWrapper.java
//

#include "J2ObjC_source.h"
#include "es/gob/jmulticard/card/InvalidCardException.h"
#include "es/gob/jmulticard/card/dnie/BurnedDnieCardException.h"
#include "es/gob/jmulticard/card/dnie/Dnie.h"
#include "es/gob/jmulticard/card/dnie/DnieFactory.h"
#include "es/gob/jmulticard/card/dnie/InvalidAccessCodeException.h"
#include "es/gob/jmulticard/card/icao/MrtdLds1.h"
#include "es/gob/jmulticard/connection/ApduConnection.h"
#include "es/gob/jmulticard/connection/ApduConnectionException.h"
#include "es/gob/jmulticard/crypto/BcCryptoHelper.h"
#include "es/gob/jmulticard/ios/DnieFactoryWrapper.h"
#include "es/gob/jmulticard/ios/DnieInfoWrapper.h"
#include "es/gob/jmulticard/ios/DnieWrapper.h"
#include "es/gob/jmulticard/ios/ErrorCode.h"
#include "java/lang/Throwable.h"
#include "javax/security/auth/callback/CallbackHandler.h"

#if !__has_feature(objc_arc)
#error "es/gob/jmulticard/ios/DnieFactoryWrapper must be compiled with ARC (-fobjc-arc)"
#endif

#line 1 "/Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/es/gob/jmulticard/ios/DnieFactoryWrapper.java"


#line 18
@implementation EsGobJmulticardIosDnieFactoryWrapper

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 18
- (instancetype)init {
  EsGobJmulticardIosDnieFactoryWrapper_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 28
+ (EsGobJmulticardIosDnieWrapper *)getDnieWithEsGobJmulticardConnectionApduConnection:(id<EsGobJmulticardConnectionApduConnection>)conn
                                         withJavaxSecurityAuthCallbackCallbackHandler:(id<JavaxSecurityAuthCallbackCallbackHandler>)callbackHandler {
  return EsGobJmulticardIosDnieFactoryWrapper_getDnieWithEsGobJmulticardConnectionApduConnection_withJavaxSecurityAuthCallbackCallbackHandler_(conn, callbackHandler);
}


#line 71
+ (EsGobJmulticardIosDnieInfoWrapper *)getDnieInfoWithEsGobJmulticardConnectionApduConnection:(id<EsGobJmulticardConnectionApduConnection>)conn
                                                 withJavaxSecurityAuthCallbackCallbackHandler:(id<JavaxSecurityAuthCallbackCallbackHandler>)callbackHandler {
  return EsGobJmulticardIosDnieFactoryWrapper_getDnieInfoWithEsGobJmulticardConnectionApduConnection_withJavaxSecurityAuthCallbackCallbackHandler_(conn, callbackHandler);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LEsGobJmulticardIosDnieWrapper;", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "LEsGobJmulticardIosDnieInfoWrapper;", 0x9, 2, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getDnieWithEsGobJmulticardConnectionApduConnection:withJavaxSecurityAuthCallbackCallbackHandler:);
  methods[2].selector = @selector(getDnieInfoWithEsGobJmulticardConnectionApduConnection:withJavaxSecurityAuthCallbackCallbackHandler:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "getDnie", "LEsGobJmulticardConnectionApduConnection;LJavaxSecurityAuthCallbackCallbackHandler;", "getDnieInfo" };
  static const J2ObjcClassInfo _EsGobJmulticardIosDnieFactoryWrapper = { "DnieFactoryWrapper", "es.gob.jmulticard.ios", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_EsGobJmulticardIosDnieFactoryWrapper;
}

@end


#line 18
void EsGobJmulticardIosDnieFactoryWrapper_init(EsGobJmulticardIosDnieFactoryWrapper *self) {
  NSObject_init(self);
}


#line 18
EsGobJmulticardIosDnieFactoryWrapper *new_EsGobJmulticardIosDnieFactoryWrapper_init() {
  J2OBJC_NEW_IMPL(EsGobJmulticardIosDnieFactoryWrapper, init)
}


#line 18
EsGobJmulticardIosDnieFactoryWrapper *create_EsGobJmulticardIosDnieFactoryWrapper_init() {
  J2OBJC_CREATE_IMPL(EsGobJmulticardIosDnieFactoryWrapper, init)
}


#line 28
EsGobJmulticardIosDnieWrapper *EsGobJmulticardIosDnieFactoryWrapper_getDnieWithEsGobJmulticardConnectionApduConnection_withJavaxSecurityAuthCallbackCallbackHandler_(id<EsGobJmulticardConnectionApduConnection> conn, id<JavaxSecurityAuthCallbackCallbackHandler> callbackHandler) {
  EsGobJmulticardIosDnieFactoryWrapper_initialize();
  EsGobJmulticardCardDnieDnie *dnie = nil;
  jint errorCode = -1;
  NSString *errorMessage = nil;
  @try {
    dnie = EsGobJmulticardCardDnieDnieFactory_getDnieWithEsGobJmulticardConnectionApduConnection_withJavaxSecurityAuthCallbackPasswordCallback_withEsGobJmulticardCryptoHelper_withJavaxSecurityAuthCallbackCallbackHandler_(conn, nil, new_EsGobJmulticardCryptoBcCryptoHelper_init(), callbackHandler);
  }
  @catch (
#line 35
  EsGobJmulticardCardInvalidCardException *e) {
    errorCode = EsGobJmulticardIosErrorCode_INVALID_CARD;
    errorMessage = [e getMessage];
  }
  @catch (
#line 38
  EsGobJmulticardCardDnieBurnedDnieCardException *e) {
    errorCode = EsGobJmulticardIosErrorCode_BURNED_CARD;
    errorMessage = [e getMessage];
  }
  @catch (
#line 41
  EsGobJmulticardCardDnieInvalidAccessCodeException *e) {
    errorCode = EsGobJmulticardIosErrorCode_BAD_CAN;
    errorMessage = [e getMessage];
  }
  @catch (
#line 44
  EsGobJmulticardConnectionApduConnectionException *e) {
    errorCode = EsGobJmulticardIosErrorCode_CONNECTION_ERROR;
    errorMessage = [e getMessage];
  }
  @catch (
#line 47
  JavaLangThrowable *e) {
    errorCode = EsGobJmulticardIosErrorCode_SEVERE_ERROR;
    errorMessage = [e description];
  }
  
#line 53
  EsGobJmulticardIosDnieWrapper *result;
  if (dnie != nil) {
    result = new_EsGobJmulticardIosDnieWrapper_initWithEsGobJmulticardCardDnieDnie_(dnie);
  }
  else {
    
#line 57
    result = new_EsGobJmulticardIosDnieWrapper_initWithInt_withNSString_(errorCode, errorMessage);
  }
  
#line 60
  return result;
}


#line 71
EsGobJmulticardIosDnieInfoWrapper *EsGobJmulticardIosDnieFactoryWrapper_getDnieInfoWithEsGobJmulticardConnectionApduConnection_withJavaxSecurityAuthCallbackCallbackHandler_(id<EsGobJmulticardConnectionApduConnection> conn, id<JavaxSecurityAuthCallbackCallbackHandler> callbackHandler) {
  EsGobJmulticardIosDnieFactoryWrapper_initialize();
  id<EsGobJmulticardCardIcaoMrtdLds1> icaoInfo = nil;
  jint errorCode = -1;
  NSString *errorMessage = nil;
  @try {
    icaoInfo = EsGobJmulticardCardDnieDnieFactory_getEmrtdNfcWithEsGobJmulticardConnectionApduConnection_withEsGobJmulticardCryptoHelper_withJavaxSecurityAuthCallbackCallbackHandler_(conn, new_EsGobJmulticardCryptoBcCryptoHelper_init(), callbackHandler);
  }
  @catch (
#line 78
  EsGobJmulticardCardDnieInvalidAccessCodeException *e) {
    errorCode = EsGobJmulticardIosErrorCode_BAD_CAN;
    errorMessage = [e getMessage];
  }
  @catch (
#line 81
  EsGobJmulticardConnectionApduConnectionException *e) {
    errorCode = EsGobJmulticardIosErrorCode_CONNECTION_ERROR;
    errorMessage = [e getMessage];
  }
  @catch (
#line 84
  JavaLangThrowable *e) {
    errorCode = EsGobJmulticardIosErrorCode_SEVERE_ERROR;
    errorMessage = [e description];
  }
  
#line 90
  EsGobJmulticardIosDnieInfoWrapper *result;
  if (icaoInfo != nil) {
    result = new_EsGobJmulticardIosDnieInfoWrapper_initWithEsGobJmulticardCardIcaoMrtdLds1_(icaoInfo);
  }
  else {
    
#line 94
    result = new_EsGobJmulticardIosDnieInfoWrapper_initWithInt_withNSString_(errorCode, errorMessage);
  }
  
#line 97
  return result;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EsGobJmulticardIosDnieFactoryWrapper)
