//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/es/gob/jmulticard/ios/DnieInfo.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "es/gob/jmulticard/ios/DnieInfo.h"

#if !__has_feature(objc_arc)
#error "es/gob/jmulticard/ios/DnieInfo must be compiled with ARC (-fobjc-arc)"
#endif

@interface EsGobJmulticardIosDnieInfo () {
 @public
  /*!
   @brief N&uacute;mero de documento.
   */
  NSString *docNumber_;
  /*!
   @brief N&uacute;mero de DNI.
   */
  NSString *dniNumber_;
  /*!
   @brief Nombre.
   */
  NSString *name_;
  /*!
   @brief Apellidos.
   */
  NSString *surname_;
  /*!
   @brief G&eacute;neros.
   */
  NSString *gender_;
  /*!
   @brief Nacionalidad.
   */
  NSString *nationality_;
  /*!
   @brief Direcci&oacute;n.
   */
  NSString *residenceAddress_;
  /*!
   @brief Ciudad.
   */
  NSString *residenceCity_;
  /*!
   @brief Provincia.
   */
  NSString *residenceProvince_;
  /*!
   @brief Ciudad de nacimiento.
   */
  NSString *birthCity_;
  /*!
   @brief Provincia de nacimiento.
   */
  NSString *birthProvince_;
  /*!
   @brief Pa&iacute;s de nacimiento.
   */
  NSString *birthCountry_;
  /*!
   @brief Fecha de nacimiento en formato dd/MM/yyyy.
   */
  NSString *dateOfBirth_;
  /*!
   @brief Fecha de caducidad en formato dd/MM/yyyy.
   */
  NSString *dateOfExpiry_;
  /*!
   @brief Foto de la cara (JPEG 2000).
   */
  IOSByteArray *facePhoto_;
  /*!
   @brief Foto de la firma (JPEG 2000).
   */
  IOSByteArray *signaturePhoto_;
}

@end

J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, docNumber_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, dniNumber_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, name_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, surname_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, gender_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, nationality_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, residenceAddress_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, residenceCity_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, residenceProvince_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, birthCity_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, birthProvince_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, birthCountry_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, dateOfBirth_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, dateOfExpiry_, NSString *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, facePhoto_, IOSByteArray *)
J2OBJC_FIELD_SETTER(EsGobJmulticardIosDnieInfo, signaturePhoto_, IOSByteArray *)

#line 1 "/Users/desarrolloabamobile/Downloads/jmulticard-ios/src/main/java/es/gob/jmulticard/ios/DnieInfo.java"


#line 6
@implementation EsGobJmulticardIosDnieInfo

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 6
- (instancetype)init {
  EsGobJmulticardIosDnieInfo_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 45
- (NSString *)getDocNumber {
  return self->docNumber_;
}


#line 53
- (void)setDocNumberWithNSString:(NSString *)docNumber {
  self->docNumber_ = docNumber;
}


#line 61
- (NSString *)getDniNumber {
  return self->dniNumber_;
}


#line 69
- (void)setDniNumberWithNSString:(NSString *)dniNumber {
  self->dniNumber_ = dniNumber;
}


#line 77
- (NSString *)getName {
  return self->name_;
}


#line 85
- (void)setNameWithNSString:(NSString *)name {
  self->name_ = name;
}


#line 93
- (NSString *)getSurname {
  return self->surname_;
}


#line 101
- (void)setSurnameWithNSString:(NSString *)surname {
  self->surname_ = surname;
}


#line 109
- (NSString *)getGender {
  return self->gender_;
}


#line 117
- (void)setGenderWithNSString:(NSString *)gender {
  self->gender_ = gender;
}


#line 125
- (NSString *)getNationality {
  return self->nationality_;
}


#line 133
- (void)setNationalityWithNSString:(NSString *)nationality {
  self->nationality_ = nationality;
}


#line 141
- (NSString *)getResidenceAddress {
  return self->residenceAddress_;
}


#line 149
- (void)setResidenceAddressWithNSString:(NSString *)residenceProvince {
  self->residenceAddress_ = residenceProvince;
}


#line 157
- (NSString *)getResidenceCity {
  return self->residenceCity_;
}


#line 165
- (void)setResidenceCityWithNSString:(NSString *)residenceProvince {
  self->residenceCity_ = residenceProvince;
}


#line 173
- (NSString *)getResidenceProvince {
  return self->residenceProvince_;
}


#line 181
- (void)setResidenceProvinceWithNSString:(NSString *)residenceProvince {
  self->residenceProvince_ = residenceProvince;
}


#line 189
- (NSString *)getBirthCity {
  return self->birthCity_;
}


#line 197
- (void)setBirthCityWithNSString:(NSString *)birthCity {
  self->birthCity_ = birthCity;
}


#line 205
- (NSString *)getBirthProvince {
  return self->birthProvince_;
}


#line 213
- (void)setBirthProvinceWithNSString:(NSString *)birthProvince {
  self->birthProvince_ = birthProvince;
}


#line 221
- (NSString *)getBirthCountry {
  return self->birthCountry_;
}


#line 229
- (void)setBirthCountryWithNSString:(NSString *)birthCountry {
  self->birthCountry_ = birthCountry;
}


#line 237
- (NSString *)getDateOfBirth {
  return self->dateOfBirth_;
}


#line 245
- (void)setDateOfBirthWithNSString:(NSString *)dateOfBirth {
  self->dateOfBirth_ = dateOfBirth;
}


#line 253
- (NSString *)getDateOfExpiry {
  return self->dateOfExpiry_;
}


#line 261
- (void)setDateOfExpiryWithNSString:(NSString *)dateOfExpiry {
  self->dateOfExpiry_ = dateOfExpiry;
}


#line 269
- (IOSByteArray *)getFacePhoto {
  return self->facePhoto_;
}


#line 277
- (void)setFacePhotoWithByteArray:(IOSByteArray *)facePhoto {
  self->facePhoto_ = facePhoto;
}


#line 285
- (IOSByteArray *)getSignaturePhoto {
  return self->signaturePhoto_;
}


#line 293
- (void)setSignaturePhotoWithByteArray:(IOSByteArray *)signaturePhoto {
  self->signaturePhoto_ = signaturePhoto;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 0, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 2, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 3, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 4, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 5, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 6, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 7, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 8, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 9, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 10, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 11, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 12, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 13, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 14, 1, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 15, 16, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x0, 17, 16, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getDocNumber);
  methods[2].selector = @selector(setDocNumberWithNSString:);
  methods[3].selector = @selector(getDniNumber);
  methods[4].selector = @selector(setDniNumberWithNSString:);
  methods[5].selector = @selector(getName);
  methods[6].selector = @selector(setNameWithNSString:);
  methods[7].selector = @selector(getSurname);
  methods[8].selector = @selector(setSurnameWithNSString:);
  methods[9].selector = @selector(getGender);
  methods[10].selector = @selector(setGenderWithNSString:);
  methods[11].selector = @selector(getNationality);
  methods[12].selector = @selector(setNationalityWithNSString:);
  methods[13].selector = @selector(getResidenceAddress);
  methods[14].selector = @selector(setResidenceAddressWithNSString:);
  methods[15].selector = @selector(getResidenceCity);
  methods[16].selector = @selector(setResidenceCityWithNSString:);
  methods[17].selector = @selector(getResidenceProvince);
  methods[18].selector = @selector(setResidenceProvinceWithNSString:);
  methods[19].selector = @selector(getBirthCity);
  methods[20].selector = @selector(setBirthCityWithNSString:);
  methods[21].selector = @selector(getBirthProvince);
  methods[22].selector = @selector(setBirthProvinceWithNSString:);
  methods[23].selector = @selector(getBirthCountry);
  methods[24].selector = @selector(setBirthCountryWithNSString:);
  methods[25].selector = @selector(getDateOfBirth);
  methods[26].selector = @selector(setDateOfBirthWithNSString:);
  methods[27].selector = @selector(getDateOfExpiry);
  methods[28].selector = @selector(setDateOfExpiryWithNSString:);
  methods[29].selector = @selector(getFacePhoto);
  methods[30].selector = @selector(setFacePhotoWithByteArray:);
  methods[31].selector = @selector(getSignaturePhoto);
  methods[32].selector = @selector(setSignaturePhotoWithByteArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "docNumber_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "dniNumber_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "name_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "surname_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "gender_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "nationality_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "residenceAddress_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "residenceCity_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "residenceProvince_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "birthCity_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "birthProvince_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "birthCountry_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "dateOfBirth_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "dateOfExpiry_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "facePhoto_", "[B", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "signaturePhoto_", "[B", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "setDocNumber", "LNSString;", "setDniNumber", "setName", "setSurname", "setGender", "setNationality", "setResidenceAddress", "setResidenceCity", "setResidenceProvince", "setBirthCity", "setBirthProvince", "setBirthCountry", "setDateOfBirth", "setDateOfExpiry", "setFacePhoto", "[B", "setSignaturePhoto" };
  static const J2ObjcClassInfo _EsGobJmulticardIosDnieInfo = { "DnieInfo", "es.gob.jmulticard.ios", ptrTable, methods, fields, 7, 0x1, 33, 16, -1, -1, -1, -1, -1 };
  return &_EsGobJmulticardIosDnieInfo;
}

@end


#line 6
void EsGobJmulticardIosDnieInfo_init(EsGobJmulticardIosDnieInfo *self) {
  NSObject_init(self);
  self->docNumber_ =
#line 9
  nil;
  self->dniNumber_ =
#line 11
  nil;
  self->name_ =
#line 13
  nil;
  self->surname_ =
#line 15
  nil;
  self->gender_ =
#line 17
  nil;
  self->nationality_ =
#line 19
  nil;
  self->residenceAddress_ =
#line 21
  nil;
  self->residenceCity_ =
#line 23
  nil;
  self->residenceProvince_ =
#line 25
  nil;
  self->birthCity_ =
#line 27
  nil;
  self->birthProvince_ =
#line 29
  nil;
  self->birthCountry_ =
#line 31
  nil;
  self->dateOfBirth_ =
#line 33
  nil;
  self->dateOfExpiry_ =
#line 35
  nil;
  self->facePhoto_ =
#line 37
  nil;
  self->signaturePhoto_ =
#line 39
  nil;
}


#line 6
EsGobJmulticardIosDnieInfo *new_EsGobJmulticardIosDnieInfo_init() {
  J2OBJC_NEW_IMPL(EsGobJmulticardIosDnieInfo, init)
}


#line 6
EsGobJmulticardIosDnieInfo *create_EsGobJmulticardIosDnieInfo_init() {
  J2OBJC_CREATE_IMPL(EsGobJmulticardIosDnieInfo, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EsGobJmulticardIosDnieInfo)
